"""Find session clusters not yet bound to any topic hub.

Backstop for the agent-side session-end binding rule (Wiki Protocol). When
the agent forgets, mis-files, or hits an edge case, this script catches it.

A cluster is "bound" when its `_summary.md` frontmatter carries at least one
`related_to` edge whose target points at `topics/` (a topic hub). A cluster
with no such edge is "unbound" and should be bound on the next session that
touches related work.

Vault-agnostic: the vault root comes from the --root argument, the WIKI_ROOT
environment variable, or the current directory (in that order). Nothing is
hardcoded to a personal vault path.

Frontmatter is parsed with PyYAML (same approach as lint_binding.py). A node
with broken or missing frontmatter is treated as having no edges — i.e.
unbound — so a half-written cluster surfaces for attention rather than being
silently skipped.

Usage:
    python scripts/bind_clusters.py --root <vault>
    WIKI_ROOT=<vault> python scripts/bind_clusters.py

Exit codes:
    0 — ran successfully (writes BINDING_QUEUE.md)
    1 — vault nodes/ directory missing
"""

import argparse
import os
import sys
from pathlib import Path

import yaml

FRONTMATTER_DELIM = "---"


def resolve_root(root=None) -> Path:
    """Resolve the vault root: explicit arg > WIKI_ROOT env > current dir."""
    if root is not None:
        return Path(root)
    env = os.environ.get("WIKI_ROOT")
    if env:
        return Path(env)
    return Path(".")


def parse_frontmatter(path: Path) -> dict:
    """Read a markdown node and return its YAML frontmatter as a dict.

    Empty dict if the file has no frontmatter block or the YAML is malformed —
    a broken-frontmatter node is treated the same as an edgeless one.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    if not text.startswith(FRONTMATTER_DELIM):
        return {}
    lines = text.split("\n")
    closing = None
    for i in range(1, len(lines)):
        if lines[i].strip() == FRONTMATTER_DELIM:
            closing = i
            break
    if closing is None:
        return {}
    try:
        parsed = yaml.safe_load("\n".join(lines[1:closing]))
    except yaml.YAMLError:
        return {}
    return parsed or {}


def has_topic_binding(frontmatter: dict) -> bool:
    """True if frontmatter has a `related_to` edge whose target is a topic hub."""
    edges = frontmatter.get("edges", [])
    if not isinstance(edges, list):
        return False
    for edge in edges:
        if not isinstance(edge, dict):
            continue
        to = edge.get("to", "")
        rel = edge.get("rel", "")
        if rel == "related_to" and isinstance(to, str) and to.startswith("topics/"):
            return True
    return False


def all_cluster_dirs(root: Path):
    """Return all `nodes/<slug>/` dirs that contain a _summary.md, sorted by name."""
    nodes = root / "nodes"
    if not nodes.is_dir():
        return []
    return [
        d for d in sorted(nodes.iterdir())
        if d.is_dir() and (d / "_summary.md").exists()
    ]


def find_unbound(root=None):
    """Return the list of cluster dirs (Path) with no topic-hub binding.

    A cluster is bound when its _summary.md has a `related_to` edge to a
    `topics/` target. Order follows directory name sort.
    """
    root = resolve_root(root)
    unbound = []
    for cluster_dir in all_cluster_dirs(root):
        fm = parse_frontmatter(cluster_dir / "_summary.md")
        if not has_topic_binding(fm):
            unbound.append(cluster_dir)
    return unbound


def build_queue(root: Path) -> tuple:
    """Build BINDING_QUEUE.md content + a stats dict."""
    clusters = all_cluster_dirs(root)
    unbound = find_unbound(root)
    bound_count = len(clusters) - len(unbound)

    lines = []
    lines.append("# Wiki binding queue")
    lines.append("")
    lines.append(
        f"Auto-generated by `scripts/bind_clusters.py`. "
        f"{bound_count} bound / {len(unbound)} unbound / "
        f"{len(clusters)} total clusters."
    )
    lines.append("")
    lines.append(
        "Per the Wiki Protocol, the agent should bind these clusters to "
        "topic hubs on the next session that touches related work. Use the "
        "manifest (`MANIFEST.md`) as the candidate hub set."
    )
    lines.append("")
    lines.append("## Unbound clusters")
    lines.append("")
    if unbound:
        lines.append(
            "Each cluster below has no `related_to topics/*` edge in its "
            "`_summary.md` frontmatter."
        )
        lines.append("")
        for cluster_dir in unbound:
            lines.append(f"- [[nodes/{cluster_dir.name}/_summary]]")
        lines.append("")
    else:
        lines.append("None — every cluster is bound to at least one hub.")
        lines.append("")

    stats = {
        "total": len(clusters),
        "bound": bound_count,
        "unbound": len(unbound),
    }
    return "\n".join(lines).rstrip() + "\n", stats


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="bind_clusters",
        description="Find session clusters not bound to any topic hub.",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Vault root (default: WIKI_ROOT env var, else current dir).",
    )
    args = parser.parse_args(argv)

    root = resolve_root(args.root)
    if not (root / "nodes").is_dir():
        print(f"ERROR: {root / 'nodes'} does not exist", file=sys.stderr)
        return 1

    content, stats = build_queue(root)
    (root / "BINDING_QUEUE.md").write_text(content, encoding="utf-8")
    print(
        f"bind_clusters: total={stats['total']} "
        f"bound={stats['bound']} unbound={stats['unbound']}"
    )
    print(f"wrote {root / 'BINDING_QUEUE.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
