"""Generate the Wiki Manifest from topics/*.md.

Output: <root>/MANIFEST.md (and prints to stdout).

Designed for session-start injection — the manifest is the Layer-1
navigation backbone. The agent reads it once at session start, then uses
native LLM semantic association to map the user's prompt against the hub
titles. Hub TL;DRs are truncated to keep the manifest token-cheap.

Hub discovery:
- Scans <root>/topics/*.md
- Skips README.md
- Extracts the TL;DR blockquote (first 18 words shown in manifest)

Vault-agnostic: the vault root comes from the --root argument, the
WIKI_ROOT environment variable, or the current directory (in that order
of precedence). Nothing is hardcoded to a personal vault path.

Category mapping is OPTIONAL. Pass a {category: [slug, ...]} dict to
build_manifest(categories=...) to group hubs into sections; any hub not
listed (or when no map is given) falls into an "Uncategorized" bucket so
new hubs are never silently dropped.

Usage:
    python scripts/gen_manifest.py --root <vault>
    WIKI_ROOT=<vault> python scripts/gen_manifest.py
    python scripts/gen_manifest.py            # defaults to current dir

Re-runs are safe and idempotent.
"""

import argparse
import os
import re
import sys
from pathlib import Path

# Default category bucket name for hubs that aren't explicitly mapped.
DEFAULT_CATEGORY = "Uncategorized"

TLDR_PATTERN = re.compile(
    r'>\s*\*\*TL;DR[^*]*\*\*\s*([\s\S]+?)(?:\n\n|\n##|\Z)',
)

SNIPPET_WORDS = 18


def resolve_root(root=None) -> Path:
    """Resolve the vault root: explicit arg > WIKI_ROOT env > current dir."""
    if root is not None:
        return Path(root)
    env = os.environ.get("WIKI_ROOT")
    if env:
        return Path(env)
    return Path(".")


def first_words(text: str, n: int) -> str:
    """Return first n words of text on a single line, with ellipsis if truncated."""
    words = text.strip().split()
    if not words:
        return ""
    snippet = " ".join(words[:n])
    if len(words) > n:
        snippet = snippet.rstrip(".,;:") + "…"
    return snippet


def extract_tldr(hub_path: Path) -> str:
    """Pull the TL;DR blockquote from a topic-hub markdown file.

    Returns the raw TL;DR text (newlines flattened to spaces), or empty
    string if not found. Tolerates hubs without TL;DRs so a half-written
    hub doesn't crash manifest generation.
    """
    try:
        content = hub_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""
    m = TLDR_PATTERN.search(content)
    if not m:
        return ""
    return m.group(1).strip().replace("\n", " ")


def discover_hubs(root: Path) -> dict:
    """Return {slug: tldr} for every hub under <root>/topics/."""
    hubs = {}
    topics = root / "topics"
    if not topics.is_dir():
        return hubs
    for p in sorted(topics.glob("*.md")):
        if p.name == "README.md":
            continue
        hubs[p.stem] = extract_tldr(p)
    return hubs


def render_manifest(hubs: dict, categories=None) -> str:
    """Render the manifest markdown from {slug: tldr}.

    `categories` is an optional {category_name: [slug, ...]} map. Hubs not
    listed in any category land under DEFAULT_CATEGORY at the bottom.
    """
    categories = categories or {}
    categorized: set = set()
    lines: list = []

    lines.append("# Wiki Manifest")
    lines.append("")
    lines.append(
        f"Auto-generated by `scripts/gen_manifest.py`. "
        f"{len(hubs)} topic hubs."
    )
    lines.append(
        "Layer-1 navigation backbone. For Layer-2 (clusters/sources) "
        "and Layer-3 (detail), descend from the relevant hub."
    )
    lines.append("")
    lines.append(
        "Scan this on every user message. If any hub title or TL;DR "
        "semantically matches the user's topic, read that hub's full "
        "TL;DR before answering, and announce: *\"Manifest hit: [[X]], "
        "[[Y]] — reading TL;DRs.\"* If nothing matches, announce: "
        "*\"No manifest hits — no wiki walk.\"*"
    )
    lines.append("")

    for category, slugs in categories.items():
        present = [s for s in slugs if s in hubs]
        if not present:
            continue
        lines.append(f"## {category}")
        lines.append("")
        for slug in present:
            categorized.add(slug)
            snippet = first_words(hubs[slug], SNIPPET_WORDS)
            line = f"- [[topics/{slug}]]"
            if snippet:
                line += f" — {snippet}"
            lines.append(line)
        lines.append("")

    uncategorized = sorted(s for s in hubs if s not in categorized)
    if uncategorized:
        lines.append(f"## {DEFAULT_CATEGORY}")
        lines.append("")
        for slug in uncategorized:
            snippet = first_words(hubs[slug], SNIPPET_WORDS)
            line = f"- [[topics/{slug}]]"
            if snippet:
                line += f" — {snippet}"
            lines.append(line)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def build_manifest(root=None, categories=None) -> str:
    """Discover hubs under <root>/topics/ and render the manifest markdown."""
    root = resolve_root(root)
    hubs = discover_hubs(root)
    return render_manifest(hubs, categories=categories)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_manifest",
        description="Generate MANIFEST.md from a vault's topics/ hubs.",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Vault root (default: WIKI_ROOT env var, else current dir).",
    )
    args = parser.parse_args(argv)

    root = resolve_root(args.root)
    topics = root / "topics"
    if not topics.is_dir():
        print(f"ERROR: {topics} does not exist", file=sys.stderr)
        return 1

    manifest = build_manifest(root=root)
    out = root / "MANIFEST.md"
    out.write_text(manifest, encoding="utf-8")

    # Some consoles default to a non-UTF-8 codec; force utf-8 so the stdout
    # echo never crashes on non-Latin-1 chars in hub TL;DRs.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
    sys.stdout.write(manifest)
    print(f"\n# wrote manifest to {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
